version: '3'

services:
  mongodb:
    container_name: woc_mongo
    image: mongodb/mongodb-community-server:7.0.2-ubi8
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - fetcher

  fetcher:
    container_name: woc_fetcher
    image: rebmahcs/warapi_fetcher:1.0.0-SNAPSHOT
    entrypoint: ["/bin/sh"]
    environment:
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://mongodb:27017
    networks:
      - fetcher


volumes:
  mongodb_data:

networks:
  fetcher: