warapi_fetcher:
  shards: 
    - name: "Able"
      URI: "https://war-service-live.foxholeservices.com/api"
    - name: "Bravo"
      URI: "https://war-service-live-2.foxholeservices.com/api"
    - name: "Charlie"
      URI: "https://war-service-live-3.foxholeservices.com/api"
    
